/**
 * Export utility for campaign analysis
 * Generates comprehensive Markdown export of all visible analysis modules
 */

export function exportAnalysis(concept: string, persona: string, region: string): string {
  const projectId = localStorage.getItem('activeProjectId') || 'local'
  const timestamp = new Date().toLocaleString()

  // Collect all data from localStorage
  const debrief = safeJSON(`debrief:${projectId}`)
  const opportunities = safeJSON(`opps:${projectId}`)
  const narrativeBlocks = safeJSON(`nf:${projectId}`) as any[] || []
  const scoring = safeJSON(`score:${projectId}`)
  const conversation = safeJSON(`conv:${projectId}`) as any[] || []

  // Build Markdown document
  let markdown = `# Campaign Analysis Export\n\n`
  markdown += `**Generated:** ${timestamp}\n\n`
  markdown += `---\n\n`

  // Campaign Overview
  markdown += `## Campaign Overview\n\n`
  markdown += `**Concept:** ${concept}\n\n`
  markdown += `**Target Persona:** ${persona}\n\n`
  markdown += `**Region:** ${region}\n\n`
  markdown += `---\n\n`

  // DEBRIEF
  if (debrief) {
    markdown += `## Strategic Debrief\n\n`
    if (debrief.brief) markdown += `${debrief.brief}\n\n`
    if (debrief.summary) markdown += `**Core Insight:** ${debrief.summary}\n\n`

    if (debrief.keyPoints && Array.isArray(debrief.keyPoints)) {
      markdown += `### Key Strategic Points\n\n`
      debrief.keyPoints.forEach((point: string) => {
        markdown += `- ${point}\n`
      })
      markdown += `\n`
    }

    if (debrief.didYouKnow && Array.isArray(debrief.didYouKnow)) {
      markdown += `### Market Insights\n\n`
      debrief.didYouKnow.forEach((insight: string) => {
        markdown += `- ${insight}\n`
      })
      markdown += `\n`
    }
    markdown += `---\n\n`
  }

  // OPPORTUNITIES
  if (opportunities && opportunities.opportunities && Array.isArray(opportunities.opportunities)) {
    markdown += `## Ranked Opportunities\n\n`
    opportunities.opportunities.forEach((opp: any, i: number) => {
      markdown += `### ${i + 1}. ${opp.title || 'Opportunity'}\n\n`
      if (opp.rationale) markdown += `${opp.rationale}\n\n`
      if (typeof opp.impact === 'number') markdown += `**Impact Score:** ${opp.impact}/100\n\n`
    })
    markdown += `---\n\n`
  }

  // NARRATIVE FRAMEWORK
  if (narrativeBlocks.length > 0) {
    markdown += `## Narrative Framework\n\n`
    narrativeBlocks.forEach((block: any) => {
      if (block.content && block.content.trim()) {
        markdown += `### ${block.title}\n\n`
        markdown += `${block.content}\n\n`
      }
    })
    markdown += `---\n\n`
  }

  // SCORING
  if (scoring) {
    markdown += `## Campaign Scoring\n\n`

    const scores = scoring.scores || {}
    if (Object.keys(scores).length > 0) {
      markdown += `### Framework Scores\n\n`
      markdown += `| Dimension | Score |\n`
      markdown += `|-----------|-------|\n`
      Object.entries(scores).forEach(([key, value]: [string, any]) => {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
        const score = typeof value === 'number' ? value : '—'
        markdown += `| ${label} | ${score} |\n`
      })
      markdown += `\n`
    }

    const ralph = scoring.ralph || {}
    if (Object.keys(ralph).length > 0) {
      markdown += `### RALPH Framework\n\n`
      markdown += `| Dimension | Score |\n`
      markdown += `|-----------|-------|\n`
      Object.entries(ralph).forEach(([key, value]: [string, any]) => {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
        const score = typeof value === 'number' ? value : '—'
        markdown += `| ${label} | ${score} |\n`
      })
      markdown += `\n`
    }

    markdown += `---\n\n`
  }

  // CO-PILOT CONVERSATION
  if (conversation.length > 0) {
    markdown += `## Co-Pilot Conversation\n\n`
    conversation.forEach((msg: any) => {
      const role = msg.role === 'user' ? 'You' : 'Co-Pilot'
      markdown += `**${role}:** ${msg.content}\n\n`
    })
    markdown += `---\n\n`
  }

  // Footer
  markdown += `\n\n*Generated by PulseEngine Storytelling Intelligence • ${timestamp}*\n`

  return markdown
}

/**
 * Download Markdown content as a file
 */
export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Copy Markdown to clipboard
 */
export async function copyToClipboard(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content)
    return true
  } catch (err) {
    console.error('Failed to copy to clipboard:', err)
    return false
  }
}

function safeJSON(key: string): any {
  try {
    return JSON.parse(localStorage.getItem(key) || 'null')
  } catch {
    return null
  }
}
