/**
 * Export utility for campaign analysis
 * Generates comprehensive Markdown export of all visible analysis modules
 */

export function exportAnalysis(concept: string, persona: string, region: string): string {
  const projectId = localStorage.getItem('activeProjectId') || 'local'
  const timestamp = new Date().toLocaleString()

  // Collect all data from localStorage
  const debrief = safeJSON(`debrief:${projectId}`)
  const opportunities = safeJSON(`opps:${projectId}`)
  const narrativeBlocks = safeJSON(`nf:${projectId}`) as any[] || []
  const scoring = safeJSON(`score:${projectId}`)
  const conversation = safeJSON(`conv:${projectId}`) as any[] || []

  // Build Markdown document
  let markdown = `# Campaign Analysis Export\n\n`
  markdown += `**Generated:** ${timestamp}\n\n`
  markdown += `---\n\n`

  // Campaign Overview
  markdown += `## Campaign Overview\n\n`
  markdown += `**Concept:** ${concept}\n\n`
  markdown += `**Target Persona:** ${persona}\n\n`
  markdown += `**Region:** ${region}\n\n`
  markdown += `---\n\n`

  // DEBRIEF
  if (debrief) {
    markdown += `## Strategic Debrief\n\n`
    if (debrief.brief) markdown += `${debrief.brief}\n\n`
    if (debrief.summary) markdown += `**Core Insight:** ${debrief.summary}\n\n`

    if (debrief.keyPoints && Array.isArray(debrief.keyPoints)) {
      markdown += `### Key Strategic Points\n\n`
      debrief.keyPoints.forEach((point: string) => {
        markdown += `- ${point}\n`
      })
      markdown += `\n`
    }

    if (debrief.didYouKnow && Array.isArray(debrief.didYouKnow)) {
      markdown += `### Market Insights\n\n`
      debrief.didYouKnow.forEach((insight: string) => {
        markdown += `- ${insight}\n`
      })
      markdown += `\n`
    }
    markdown += `---\n\n`
  }

  // OPPORTUNITIES
  if (opportunities && opportunities.opportunities && Array.isArray(opportunities.opportunities)) {
    markdown += `## Ranked Opportunities\n\n`
    opportunities.opportunities.forEach((opp: any, i: number) => {
      markdown += `### ${i + 1}. ${opp.title || 'Opportunity'}\n\n`
      if (opp.rationale) markdown += `${opp.rationale}\n\n`
      if (typeof opp.impact === 'number') markdown += `**Impact Score:** ${opp.impact}/100\n\n`
    })
    markdown += `---\n\n`
  }

  // NARRATIVE FRAMEWORK
  if (narrativeBlocks.length > 0) {
    markdown += `## Narrative Framework\n\n`
    narrativeBlocks.forEach((block: any) => {
      if (block.content && block.content.trim()) {
        markdown += `### ${block.title}\n\n`
        markdown += `${block.content}\n\n`
      }
    })
    markdown += `---\n\n`
  }

  // SCORING
  if (scoring) {
    markdown += `## Campaign Scoring\n\n`

    const scores = scoring.scores || {}
    if (Object.keys(scores).length > 0) {
      markdown += `### Framework Scores\n\n`
      markdown += `| Dimension | Score |\n`
      markdown += `|-----------|-------|\n`
      Object.entries(scores).forEach(([key, value]: [string, any]) => {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
        const score = typeof value === 'number' ? value : '—'
        markdown += `| ${label} | ${score} |\n`
      })
      markdown += `\n`
    }

    const ralph = scoring.ralph || {}
    if (Object.keys(ralph).length > 0) {
      markdown += `### RALPH Framework\n\n`
      markdown += `| Dimension | Score |\n`
      markdown += `|-----------|-------|\n`
      Object.entries(ralph).forEach(([key, value]: [string, any]) => {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
        const score = typeof value === 'number' ? value : '—'
        markdown += `| ${label} | ${score} |\n`
      })
      markdown += `\n`
    }

    markdown += `---\n\n`
  }

  // CO-PILOT CONVERSATION
  if (conversation.length > 0) {
    markdown += `## Co-Pilot Conversation\n\n`
    conversation.forEach((msg: any) => {
      const role = msg.role === 'user' ? 'You' : 'Co-Pilot'
      markdown += `**${role}:** ${msg.content}\n\n`
    })
    markdown += `---\n\n`
  }

  // Footer
  markdown += `\n\n*Generated by PulseEngine Storytelling Intelligence • ${timestamp}*\n`

  return markdown
}

export function exportProjectFull(concept: string, persona: string, region: string): string {
  const projectId = localStorage.getItem('activeProjectId') || 'local'
  const timestamp = new Date().toLocaleString()
  const targetAudience = (() => { try { return localStorage.getItem('targetAudience') || '' } catch { return '' } })()
  const debrief = safeJSON(`debrief:${projectId}`)
  const opportunities = safeJSON(`opps:${projectId}`)
  const narrativeBlocks = safeJSON(`nf:${projectId}`) as any[] || []
  const scoring = safeJSON(`score:${projectId}`)
  const conversation = safeJSON(`conv:${projectId}`) as any[] || []
  const wildcard = safeJSON(`wild:${projectId}`)

  let md = `# Project Export\n\nGenerated ${timestamp}\n\n---\n\n`
  md += `## Overview\n\n- Concept: ${concept}\n- Persona (user role): ${persona || '—'}\n- Target Audience: ${targetAudience || '—'}\n- Region: ${region || '—'}\n- Project ID: ${projectId}\n\n`

  // Sources
  if (debrief?.sources) {
    md += `## Sources Used (This Pass)\n\n`
    const s = debrief.sources
    const list = (label: string, arr?: any[]) => {
      if (!arr || arr.length === 0) return
      md += `### ${label} (${arr.length})\n\n`
      arr.forEach((v: any) => { md += `- ${String(v)}\n` })
      md += `\n`
    }
    list('Project Files', s.project)
    list('RKB', s.core)
    list('Live Trends', s.live)
  }

  // Debrief
  if (debrief) {
    md += `---\n\n## Strategic Debrief\n\n`
    if (targetAudience) {
      md += `**Target Audience:** ${targetAudience}\n\n`
    }
    if (debrief._debug?.prompt) {
      md += `<details><summary>Prompt</summary>\n\n\n\n\n${codeBlock(debrief._debug.prompt)}\n\n</details>\n\n`
    }
    if (debrief.brief) md += `${debrief.brief}\n\n`
    if (debrief.summary) md += `**Core Insight:** ${debrief.summary}\n\n`
    if (Array.isArray(debrief.keyPoints)) {
      md += `### Key Points\n\n` + debrief.keyPoints.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
    if (Array.isArray(debrief.didYouKnow)) {
      md += `### Did You Know\n\n` + debrief.didYouKnow.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
    if (Array.isArray(debrief.personaNotes) && debrief.personaNotes.length) {
      md += `### Persona Notes\n\n` + debrief.personaNotes.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
  }

  // Opportunities
  if (opportunities) {
    md += `---\n\n## Opportunities\n\n`
    if (opportunities._debug?.prompt) {
      md += `<details><summary>Prompt</summary>\n\n${codeBlock(opportunities._debug.prompt)}\n\n</details>\n\n`
    }
    const list = Array.isArray(opportunities.opportunities) ? opportunities.opportunities : []
    list.forEach((o: any, i: number) => {
      md += `### ${i + 1}. ${o.title || 'Opportunity'}\n\n`
      if (o.why) md += `${o.why}\n\n`
      if (typeof o.impact === 'number') md += `Impact: ${o.impact}/100\n\n`
    })
    if (Array.isArray(opportunities.personaNotes) && opportunities.personaNotes.length) {
      md += `### Persona Notes\n\n` + opportunities.personaNotes.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
  }

  // Narrative
  if (narrativeBlocks.length) {
    md += `---\n\n## Narrative\n\n`
    narrativeBlocks.forEach((b: any) => {
      if (b?.content) {
        md += `### ${b.title || b.key}\n\n${b.content}\n\n`
      }
    })
  }

  // Scoring
  if (scoring?.scores) {
    md += `---\n\n## Scoring\n\n`
    Object.entries(scoring.scores).forEach(([k, v]: any) => { md += `- ${k}: ${v}\n` })
    md += `\n`
  }

  // Wildcard
  if (wildcard?.ideas) {
    md += `---\n\n## Wildcard Insight\n\n`
    if (wildcard._debug?.prompt) md += `<details><summary>Prompt</summary>\n\n${codeBlock(wildcard._debug.prompt)}\n\n</details>\n\n`
    wildcard.ideas.forEach((idea: any, idx: number) => {
      md += `### ${idx + 1}. ${idea.title}\n\n`
      if (Array.isArray(idea.contrarianWhy)) md += `Why Contrarian:\n\n` + idea.contrarianWhy.map((x: string) => `- ${x}`).join('\n') + `\n\n`
      if (Array.isArray(idea.evidence)) md += `Evidence: ${idea.evidence.join(', ')}\n\n`
      if (idea.upside) md += `Upside: ${idea.upside}\n\n`
      if (Array.isArray(idea.risks)) md += `Risks:\n\n` + idea.risks.map((x: string) => `- ${x}`).join('\n') + `\n\n`
      if (Array.isArray(idea.testPlan)) md += `Test Plan:\n\n` + idea.testPlan.map((x: string) => `- ${x}`).join('\n') + `\n\n`
      if (idea.firstStep) md += `First Step: ${idea.firstStep}\n\n`
    })
  }

  // Conversation (optional)
  if (conversation.length) {
    md += `---\n\n## Conversation\n\n`
    conversation.forEach((msg: any) => { md += `- ${msg.role}: ${msg.content}\n` })
    md += `\n`
  }

  md += `\n---\n\n*End of export — ${timestamp}*\n`
  return md
}

function codeBlock(s: string): string {
  const escaped = s.replace(/```/g, '\n\n')
  return '```\n' + escaped + '\n```'
}

/**
 * Download Markdown content as a file
 */
export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export Concept Overview as a formatted PDF via print
 * Collects full workflow: debrief, narrative, opportunities, enhancements, scores, wildcard
 */
export function exportOverviewPdf(
  concept: string,
  overviewMarkdown: string,
  opts?: { persona?: string; region?: string; opps?: { title: string; why?: string; impact?: number }[]; enhancements?: string[]; scores?: any; narrativeBlocks?: any[]; debrief?: any; wildcard?: any }
) {
  const projectId = localStorage.getItem('activeProjectId') || 'local'
  const persona = opts?.persona || (localStorage.getItem('persona') || '').replace(/\"/g,'')
  const region = opts?.region || (localStorage.getItem('region') || '').replace(/\"/g,'')
  const targetAudience = (localStorage.getItem('targetAudience') || '').replace(/\"/g,'')
  const scores = opts?.scores || safeJSON(`score:${projectId}`) || {}
  const oppsStore = safeJSON(`opps:${projectId}`)
  const opps = Array.isArray(opts?.opps) ? opts!.opps! : (Array.isArray(oppsStore?.opportunities) ? oppsStore.opportunities : [])
  const enhancements = Array.isArray(opts?.enhancements) ? opts!.enhancements! : []
  const debrief = opts?.debrief || safeJSON(`debrief:${projectId}`)
  const narrativeBlocks = opts?.narrativeBlocks || safeJSON(`nf:${projectId}`) || []
  const wildcard = opts?.wildcard || safeJSON(`wild:${projectId}`)

  // Enhanced Markdown -> HTML conversion
  const mdToHtml = (md: string): string => {
    let t = (md || '')
    // Escape HTML first
    t = t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    // Handle headings (### -> h3, ## -> h2)
    t = t.replace(/^###\s+(.*)$/gm, '<h3 class="section-heading">$1</h3>')
    t = t.replace(/^##\s+(.*)$/gm, '<h2 class="section-heading">$1</h2>')
    // Bold text
    t = t.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    // Bullet lists
    t = t.replace(/^(?:- |\* )(.*)$/gm, '<li>$1</li>')
    t = t.replace(/(<li>.*?<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    // Paragraphs
    t = t.replace(/\n\n+/g, '</p><p class="para">')
    return `<p class="para">${t}</p>`
  }

  const overviewHtml = mdToHtml(overviewMarkdown)

  // DEBRIEF SECTION
  const debriefHtml = (() => {
    if (!debrief?.brief) return ''
    let html = `<div class="section-block"><h2 class="major-heading">Campaign Essence</h2>`
    html += `<p class="para">${escapeHtml(debrief.brief)}</p>`

    if (Array.isArray(debrief.keyPoints) && debrief.keyPoints.length > 0) {
      html += `<h3 class="section-heading">Core Story & Pillars</h3><ul>`
      debrief.keyPoints.forEach((p: string) => { html += `<li>${escapeHtml(p)}</li>` })
      html += `</ul>`
    }

    html += `</div><div class="divider"></div>`
    return html
  })()

  // NARRATIVE SECTION
  const narrativeHtml = (() => {
    if (!Array.isArray(narrativeBlocks) || narrativeBlocks.length === 0) return ''
    let html = ''
    narrativeBlocks.forEach((block: any) => {
      if (block?.content && block.content.trim()) {
        html += `<div class="section-block"><h3 class="section-heading">${escapeHtml(block.title || block.key)}</h3>`
        html += mdToHtml(block.content)
        html += `</div>`
      }
    })
    if (html) html += `<div class="divider"></div>`
    return html
  })()

  // OPPORTUNITIES SECTION
  const oppHtml = (() => {
    if (!opps || opps.length === 0) return ''
    let html = `<div class="section-block"><h2 class="major-heading">Top Opportunities (Specifics)</h2><ul class="opps-list">`
    opps.slice(0, 6).forEach((o: any, i: number) => {
      html += `<li><strong>${i + 1}. ${escapeHtml(o.title)}</strong>`
      if (o.why) html += ` — ${escapeHtml(o.why)}`
      if (typeof o.impact === 'number') html += ` <em>(impact ${o.impact}/100)</em>`
      html += `</li>`
    })
    html += `</ul></div><div class="divider"></div>`
    return html
  })()

  // ENHANCEMENTS SECTION
  const enhHtml = (() => {
    if (!enhancements || enhancements.length === 0) return ''
    let html = `<div class="section-block"><h2 class="major-heading">Selected Enhancements</h2><ul>`
    enhancements.slice(0, 8).forEach((e: string) => { html += `<li>${escapeHtml(e)}</li>` })
    html += `</ul></div><div class="divider"></div>`
    return html
  })()

  // WILDCARD SECTION
  const wildcardHtml = (() => {
    if (!wildcard?.ideas || !Array.isArray(wildcard.ideas) || wildcard.ideas.length === 0) return ''
    let html = `<div class="section-block"><h2 class="major-heading">Wildcard Insights</h2>`
    wildcard.ideas.slice(0, 3).forEach((idea: any, idx: number) => {
      html += `<div class="wildcard-idea"><h3 class="section-heading">${idx + 1}. ${escapeHtml(idea.title || 'Insight')}</h3>`
      if (Array.isArray(idea.contrarianWhy) && idea.contrarianWhy.length > 0) {
        html += `<p class="para"><strong>Why Contrarian:</strong></p><ul>`
        idea.contrarianWhy.forEach((w: string) => { html += `<li>${escapeHtml(w)}</li>` })
        html += `</ul>`
      }
      if (idea.upside) html += `<p class="para"><strong>Upside:</strong> ${escapeHtml(idea.upside)}</p>`
      if (Array.isArray(idea.risks) && idea.risks.length > 0) {
        html += `<p class="para"><strong>Risks:</strong></p><ul>`
        idea.risks.forEach((r: string) => { html += `<li>${escapeHtml(r)}</li>` })
        html += `</ul>`
      }
      html += `</div>`
    })
    html += `</div><div class="divider"></div>`
    return html
  })()

  // SCORES SECTION (moved to bottom)
  const scoreHtml = (() => {
    const items: string[] = []
    if (typeof scores?.narrative === 'number') items.push(`<li><strong>Cultural Relevance:</strong> ${scores.narrative}/100</li>`)
    if (typeof scores?.cross === 'number') items.push(`<li><strong>Engagement Potential:</strong> ${scores.cross}/100</li>`)
    if (typeof scores?.ttpWeeks === 'number') items.push(`<li><strong>Time to Peak:</strong> ${scores.ttpWeeks} weeks</li>`)
    if (typeof scores?.commercial === 'number') items.push(`<li><strong>Commercial Viability:</strong> ${scores.commercial}/100</li>`)
    if (typeof scores?.overall === 'number') items.push(`<li><strong>Overall Score:</strong> ${scores.overall}/100</li>`)
    if (!items.length) return ''
    return `<div class="section-block scores-section"><h2 class="major-heading">Campaign Scores</h2><ul class="scores-list">${items.join('')}</ul></div>`
  })()

  // NEXT STEPS (from debrief)
  const nextStepsHtml = (() => {
    if (!debrief) return ''
    const steps = [
      '[ ] Sharpen logline to encapsulate campaign essence and objectives.',
      '[ ] Define POV and tone that reflects warmth and community focus.',
      '[ ] Lock 3 pillars with sample segments for each.',
      '[ ] Draft a 1-page treatment detailing campaign vision and execution.',
      '[ ] Align on brand fit and establish content guardrails.',
      '[ ] Define success criteria and create a feedback loop for ongoing insights.',
      '[ ] Validate and pressure-test the selected opportunities through community surveys or focus groups.'
    ]
    return `<div class="section-block"><h2 class="major-heading">Next Steps to Finalize Concept</h2><ul class="checklist">${steps.map(s => `<li>${escapeHtml(s)}</li>`).join('')}</ul></div><div class="divider"></div>`
  })()

  // RISKS & MITIGATIONS
  const risksHtml = (() => {
    if (!debrief) return ''
    return `<div class="section-block"><h2 class="major-heading">Risks & Mitigations</h2><p class="para"><strong>Creative Risk:</strong> The storytelling may not resonate with all segments of the community. <strong>Mitigation:</strong> Conduct pre-launch surveys to gather feedback on narrative direction and adjust accordingly.</p></div>`
  })()

  // Clean filename: truncate concept to 50 chars max, kebab-case
  const cleanName = concept.slice(0, 50).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '')
  const timestamp = new Date().toISOString().slice(0, 10) // YYYY-MM-DD
  const filename = `${cleanName || 'concept'}_${timestamp}.pdf`

  const html = `<!doctype html>
  <html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(filename)}</title>
    <style>
      body {
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
        color: #111;
        line-height: 1.6;
      }
      .container { max-width: 800px; margin: 0 auto; padding: 32px; }
      h1.doc-title {
        font-size: 22px;
        margin: 0 0 12px;
        text-transform: uppercase;
        letter-spacing: .08em;
        font-weight: 700;
      }
      h2.major-heading {
        font-size: 16px;
        margin: 28px 0 12px;
        text-transform: uppercase;
        letter-spacing: .06em;
        font-weight: 600;
        color: #222;
      }
      h3.section-heading {
        font-size: 14px;
        margin: 20px 0 8px;
        text-transform: uppercase;
        letter-spacing: .05em;
        font-weight: 600;
        color: #444;
      }
      p.para {
        line-height: 1.7;
        margin: 12px 0;
        font-size: 14px;
      }
      ul {
        margin: 10px 0 16px 24px;
        line-height: 1.8;
        font-size: 14px;
      }
      ul li { margin-bottom: 6px; }
      ul.opps-list li { margin-bottom: 12px; }
      ul.checklist { list-style: none; margin-left: 0; }
      ul.checklist li { margin-bottom: 8px; }
      .meta {
        font-size: 13px;
        color: #666;
        margin-bottom: 20px;
        line-height: 1.6;
      }
      .meta div { margin: 4px 0; }
      .divider { border-top: 1px solid #ddd; margin: 28px 0; }
      .section-block { margin: 24px 0; }
      .scores-section {
        background: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
        margin: 24px 0;
      }
      .scores-list {
        list-style: none;
        margin: 12px 0 0 0;
        padding: 0;
      }
      .scores-list li {
        margin: 10px 0;
        font-size: 15px;
      }
      .wildcard-idea {
        margin-bottom: 24px;
        padding-bottom: 16px;
        border-bottom: 1px solid #eee;
      }
      .wildcard-idea:last-child { border-bottom: none; }
      @media print {
        .no-print { display: none; }
        body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1 class="doc-title">Concept Overview</h1>
      <div class="meta">
        <div><strong>Concept:</strong> ${escapeHtml(concept)}</div>
        ${persona?`<div><strong>Persona:</strong> ${escapeHtml(persona)}</div>`:''}
        ${targetAudience?`<div><strong>Target Audience:</strong> ${escapeHtml(targetAudience)}</div>`:''}
        ${region?`<div><strong>Region:</strong> ${escapeHtml(region)}</div>`:''}
        <div><strong>Generated:</strong> ${new Date().toLocaleString()}</div>
      </div>
      <div class="divider"></div>
      ${debriefHtml}
      ${narrativeHtml}
      ${oppHtml}
      ${enhHtml}
      ${wildcardHtml}
      ${scoreHtml}
      ${nextStepsHtml}
      ${risksHtml}
    </div>
    <script>
      window.onload = () => { setTimeout(()=>{ window.print() }, 300) }
    </script>
  </body>
  </html>`

  const w = window.open('', '_blank')
  if (!w) return
  w.document.open()
  w.document.write(html)
  w.document.close()
}

function escapeHtml(s: string) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;') }

/**
 * Copy Markdown to clipboard
 */
export async function copyToClipboard(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content)
    return true
  } catch (err) {
    console.error('Failed to copy to clipboard:', err)
    return false
  }
}

function safeJSON(key: string): any {
  try {
    return JSON.parse(localStorage.getItem(key) || 'null')
  } catch {
    return null
  }
}
