/**
 * Export utility for campaign analysis
 * Generates comprehensive Markdown export of all visible analysis modules
 */

export function exportAnalysis(concept: string, persona: string, region: string): string {
  const projectId = localStorage.getItem('activeProjectId') || 'local'
  const timestamp = new Date().toLocaleString()

  // Collect all data from localStorage
  const debrief = safeJSON(`debrief:${projectId}`)
  const opportunities = safeJSON(`opps:${projectId}`)
  const narrativeBlocks = safeJSON(`nf:${projectId}`) as any[] || []
  const scoring = safeJSON(`score:${projectId}`)
  const conversation = safeJSON(`conv:${projectId}`) as any[] || []

  // Build Markdown document
  let markdown = `# Campaign Analysis Export\n\n`
  markdown += `**Generated:** ${timestamp}\n\n`
  markdown += `---\n\n`

  // Campaign Overview
  markdown += `## Campaign Overview\n\n`
  markdown += `**Concept:** ${concept}\n\n`
  markdown += `**Target Persona:** ${persona}\n\n`
  markdown += `**Region:** ${region}\n\n`
  markdown += `---\n\n`

  // DEBRIEF
  if (debrief) {
    markdown += `## Strategic Debrief\n\n`
    if (debrief.brief) markdown += `${debrief.brief}\n\n`
    if (debrief.summary) markdown += `**Core Insight:** ${debrief.summary}\n\n`

    if (debrief.keyPoints && Array.isArray(debrief.keyPoints)) {
      markdown += `### Key Strategic Points\n\n`
      debrief.keyPoints.forEach((point: string) => {
        markdown += `- ${point}\n`
      })
      markdown += `\n`
    }

    if (debrief.didYouKnow && Array.isArray(debrief.didYouKnow)) {
      markdown += `### Market Insights\n\n`
      debrief.didYouKnow.forEach((insight: string) => {
        markdown += `- ${insight}\n`
      })
      markdown += `\n`
    }
    markdown += `---\n\n`
  }

  // OPPORTUNITIES
  if (opportunities && opportunities.opportunities && Array.isArray(opportunities.opportunities)) {
    markdown += `## Ranked Opportunities\n\n`
    opportunities.opportunities.forEach((opp: any, i: number) => {
      markdown += `### ${i + 1}. ${opp.title || 'Opportunity'}\n\n`
      if (opp.rationale) markdown += `${opp.rationale}\n\n`
      if (typeof opp.impact === 'number') markdown += `**Impact Score:** ${opp.impact}/100\n\n`
    })
    markdown += `---\n\n`
  }

  // NARRATIVE FRAMEWORK
  if (narrativeBlocks.length > 0) {
    markdown += `## Narrative Framework\n\n`
    narrativeBlocks.forEach((block: any) => {
      if (block.content && block.content.trim()) {
        markdown += `### ${block.title}\n\n`
        markdown += `${block.content}\n\n`
      }
    })
    markdown += `---\n\n`
  }

  // SCORING
  if (scoring) {
    markdown += `## Campaign Scoring\n\n`

    const scores = scoring.scores || {}
    if (Object.keys(scores).length > 0) {
      markdown += `### Framework Scores\n\n`
      markdown += `| Dimension | Score |\n`
      markdown += `|-----------|-------|\n`
      Object.entries(scores).forEach(([key, value]: [string, any]) => {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
        const score = typeof value === 'number' ? value : '—'
        markdown += `| ${label} | ${score} |\n`
      })
      markdown += `\n`
    }

    const ralph = scoring.ralph || {}
    if (Object.keys(ralph).length > 0) {
      markdown += `### RALPH Framework\n\n`
      markdown += `| Dimension | Score |\n`
      markdown += `|-----------|-------|\n`
      Object.entries(ralph).forEach(([key, value]: [string, any]) => {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
        const score = typeof value === 'number' ? value : '—'
        markdown += `| ${label} | ${score} |\n`
      })
      markdown += `\n`
    }

    markdown += `---\n\n`
  }

  // CO-PILOT CONVERSATION
  if (conversation.length > 0) {
    markdown += `## Co-Pilot Conversation\n\n`
    conversation.forEach((msg: any) => {
      const role = msg.role === 'user' ? 'You' : 'Co-Pilot'
      markdown += `**${role}:** ${msg.content}\n\n`
    })
    markdown += `---\n\n`
  }

  // Footer
  markdown += `\n\n*Generated by PulseEngine Storytelling Intelligence • ${timestamp}*\n`

  return markdown
}

export function exportProjectFull(concept: string, persona: string, region: string): string {
  const projectId = localStorage.getItem('activeProjectId') || 'local'
  const timestamp = new Date().toLocaleString()
  const targetAudience = (() => { try { return localStorage.getItem('targetAudience') || '' } catch { return '' } })()
  const debrief = safeJSON(`debrief:${projectId}`)
  const opportunities = safeJSON(`opps:${projectId}`)
  const narrativeBlocks = safeJSON(`nf:${projectId}`) as any[] || []
  const scoring = safeJSON(`score:${projectId}`)
  const conversation = safeJSON(`conv:${projectId}`) as any[] || []
  const wildcard = safeJSON(`wild:${projectId}`)

  let md = `# Project Export\n\nGenerated ${timestamp}\n\n---\n\n`
  md += `## Overview\n\n- Concept: ${concept}\n- Persona (user role): ${persona || '—'}\n- Target Audience: ${targetAudience || '—'}\n- Region: ${region || '—'}\n- Project ID: ${projectId}\n\n`

  // Sources
  if (debrief?.sources) {
    md += `## Sources Used (This Pass)\n\n`
    const s = debrief.sources
    const list = (label: string, arr?: any[]) => {
      if (!arr || arr.length === 0) return
      md += `### ${label} (${arr.length})\n\n`
      arr.forEach((v: any) => { md += `- ${String(v)}\n` })
      md += `\n`
    }
    list('Project Files', s.project)
    list('RKB', s.core)
    list('Live Trends', s.live)
  }

  // Debrief
  if (debrief) {
    md += `---\n\n## Strategic Debrief\n\n`
    if (targetAudience) {
      md += `**Target Audience:** ${targetAudience}\n\n`
    }
    if (debrief._debug?.prompt) {
      md += `<details><summary>Prompt</summary>\n\n\n\n\n${codeBlock(debrief._debug.prompt)}\n\n</details>\n\n`
    }
    if (debrief.brief) md += `${debrief.brief}\n\n`
    if (debrief.summary) md += `**Core Insight:** ${debrief.summary}\n\n`
    if (Array.isArray(debrief.keyPoints)) {
      md += `### Key Points\n\n` + debrief.keyPoints.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
    if (Array.isArray(debrief.didYouKnow)) {
      md += `### Did You Know\n\n` + debrief.didYouKnow.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
    if (Array.isArray(debrief.personaNotes) && debrief.personaNotes.length) {
      md += `### Persona Notes\n\n` + debrief.personaNotes.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
  }

  // Opportunities
  if (opportunities) {
    md += `---\n\n## Opportunities\n\n`
    if (opportunities._debug?.prompt) {
      md += `<details><summary>Prompt</summary>\n\n${codeBlock(opportunities._debug.prompt)}\n\n</details>\n\n`
    }
    const list = Array.isArray(opportunities.opportunities) ? opportunities.opportunities : []
    list.forEach((o: any, i: number) => {
      md += `### ${i + 1}. ${o.title || 'Opportunity'}\n\n`
      if (o.why) md += `${o.why}\n\n`
      if (typeof o.impact === 'number') md += `Impact: ${o.impact}/100\n\n`
    })
    if (Array.isArray(opportunities.personaNotes) && opportunities.personaNotes.length) {
      md += `### Persona Notes\n\n` + opportunities.personaNotes.map((p: string) => `- ${p}`).join('\n') + `\n\n`
    }
  }

  // Narrative
  if (narrativeBlocks.length) {
    md += `---\n\n## Narrative\n\n`
    narrativeBlocks.forEach((b: any) => {
      if (b?.content) {
        md += `### ${b.title || b.key}\n\n${b.content}\n\n`
      }
    })
  }

  // Scoring
  if (scoring?.scores) {
    md += `---\n\n## Scoring\n\n`
    Object.entries(scoring.scores).forEach(([k, v]: any) => { md += `- ${k}: ${v}\n` })
    md += `\n`
  }

  // Wildcard
  if (wildcard?.ideas) {
    md += `---\n\n## Wildcard Insight\n\n`
    if (wildcard._debug?.prompt) md += `<details><summary>Prompt</summary>\n\n${codeBlock(wildcard._debug.prompt)}\n\n</details>\n\n`
    wildcard.ideas.forEach((idea: any, idx: number) => {
      md += `### ${idx + 1}. ${idea.title}\n\n`
      if (Array.isArray(idea.contrarianWhy)) md += `Why Contrarian:\n\n` + idea.contrarianWhy.map((x: string) => `- ${x}`).join('\n') + `\n\n`
      if (Array.isArray(idea.evidence)) md += `Evidence: ${idea.evidence.join(', ')}\n\n`
      if (idea.upside) md += `Upside: ${idea.upside}\n\n`
      if (Array.isArray(idea.risks)) md += `Risks:\n\n` + idea.risks.map((x: string) => `- ${x}`).join('\n') + `\n\n`
      if (Array.isArray(idea.testPlan)) md += `Test Plan:\n\n` + idea.testPlan.map((x: string) => `- ${x}`).join('\n') + `\n\n`
      if (idea.firstStep) md += `First Step: ${idea.firstStep}\n\n`
    })
  }

  // Conversation (optional)
  if (conversation.length) {
    md += `---\n\n## Conversation\n\n`
    conversation.forEach((msg: any) => { md += `- ${msg.role}: ${msg.content}\n` })
    md += `\n`
  }

  md += `\n---\n\n*End of export — ${timestamp}*\n`
  return md
}

function codeBlock(s: string): string {
  const escaped = s.replace(/```/g, '\n\n')
  return '```\n' + escaped + '\n```'
}

/**
 * Download Markdown content as a file
 */
export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Export Concept Overview as a formatted PDF via print
 * Collects concept overview, key scores and top opportunities.
 */
export function exportOverviewPdf(concept: string, overviewMarkdown: string, opts?: { persona?: string; region?: string }) {
  const projectId = localStorage.getItem('activeProjectId') || 'local'
  const persona = opts?.persona || (localStorage.getItem('persona') || '').replace(/\"/g,'')
  const region = opts?.region || (localStorage.getItem('region') || '').replace(/\"/g,'')
  const targetAudience = (localStorage.getItem('targetAudience') || '').replace(/\"/g,'')
  const scores = safeJSON(`score:${projectId}`) || {}
  const opps = safeJSON(`opps:${projectId}`)

  // Minimal Markdown -> HTML conversion for the overview block
  const mdToHtml = (md: string): string => {
    let t = (md || '')
    t = t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    t = t.replace(/^###\s+(.*)$/gm, '<h3>$1</h3>')
    t = t.replace(/^(?:- |\* )(.*)$/gm, '<li>$1</li>')
    t = t.replace(/(?:(<li>[^<]*<\/li>)\n?)+/g, (m) => `<ul>${m}\n</ul>`) 
    t = t.replace(/\n\n+/g, '</p><p>')
    return `<p>${t}</p>`
  }

  const overviewHtml = mdToHtml(overviewMarkdown)
  const scoreHtml = (() => {
    const items: string[] = []
    if (typeof scores?.narrative === 'number') items.push(`<li>Cultural Relevance: ${scores.narrative}/100</li>`)
    if (typeof scores?.cross === 'number') items.push(`<li>Engagement Potential: ${scores.cross}/100</li>`)
    if (typeof scores?.ttpWeeks === 'number') items.push(`<li>Platform Fit (TTP): ${scores.ttpWeeks} weeks</li>`)
    if (typeof scores?.commercial === 'number') items.push(`<li>Commercial Viability: ${scores.commercial}/100</li>`)
    if (!items.length) return ''
    return `<h3>Key Scores</h3><ul>${items.join('')}</ul>`
  })()
  const oppHtml = (() => {
    const list = Array.isArray(opps?.opportunities) ? opps.opportunities.slice(0,5) : []
    if (!list.length) return ''
    return `<h3>Top Opportunities</h3><ul>${list.map((o:any)=>`<li>${o.title || ''}${o.impact?` — Impact ${o.impact}/100`:''}</li>`).join('')}</ul>`
  })()

  const html = `<!doctype html>
  <html>
  <head>
    <meta charset="utf-8" />
    <title>Concept Overview — ${escapeHtml(concept)}</title>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #111; }
      .container { max-width: 760px; margin: 0 auto; padding: 24px; }
      h1 { font-size: 20px; margin: 0 0 8px; text-transform: uppercase; letter-spacing: .04em; }
      h2 { font-size: 16px; margin: 18px 0 8px; text-transform: uppercase; letter-spacing: .04em; }
      h3 { font-size: 13px; margin: 16px 0 6px; text-transform: uppercase; letter-spacing: .04em; }
      p { line-height: 1.5; margin: 8px 0; }
      ul { margin: 6px 0 10px 20px; }
      .meta { font-size: 12px; color: #666; margin-bottom: 16px; }
      .divider { border-top: 1px solid #eee; margin: 16px 0; }
      @media print { .no-print { display: none } }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Concept Overview</h1>
      <div class="meta">
        <div><strong>Concept:</strong> ${escapeHtml(concept)}</div>
        ${persona?`<div><strong>Persona:</strong> ${escapeHtml(persona)}</div>`:''}
        ${targetAudience?`<div><strong>Target Audience:</strong> ${escapeHtml(targetAudience)}</div>`:''}
        ${region?`<div><strong>Region:</strong> ${escapeHtml(region)}</div>`:''}
        <div><strong>Generated:</strong> ${new Date().toLocaleString()}</div>
      </div>
      <div class="divider"></div>
      ${overviewHtml}
      ${scoreHtml}
      ${oppHtml}
    </div>
    <script>
      window.onload = () => { setTimeout(()=>{ window.print() }, 300) }
    </script>
  </body>
  </html>`

  const w = window.open('', '_blank')
  if (!w) return
  w.document.open()
  w.document.write(html)
  w.document.close()
}

function escapeHtml(s: string) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;') }

/**
 * Copy Markdown to clipboard
 */
export async function copyToClipboard(content: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(content)
    return true
  } catch (err) {
    console.error('Failed to copy to clipboard:', err)
    return false
  }
}

function safeJSON(key: string): any {
  try {
    return JSON.parse(localStorage.getItem(key) || 'null')
  } catch {
    return null
  }
}
